apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    type: frontend
spec:
  selector:
    app: {{ template "app.name" . }}
    type: frontend
  ports:
  - name: http-sv-port
    port: {{ .Values.app.port }}
    targetPort: http-port
  type: NodePort
